# Generated by Django 4.1.5 on 2023-03-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.IntegerField(),
        ),
    ]
